import {
  BarcodeFormat,
  BinaryBitmap,
  DecodeHintType,
  GlobalHistogramBinarizer,
  HybridBinarizer,
  QRCodeReader,
  RGBLuminanceSource,
  type LuminanceSource,
} from "@zxing/library";

const MAX_IMAGE_EDGE = 2400;
const hints = new Map<DecodeHintType, unknown>([
  [DecodeHintType.TRY_HARDER, true],
  [DecodeHintType.POSSIBLE_FORMATS, [BarcodeFormat.QR_CODE]],
]);

/**
 * Decode both conventional dark-on-light QR codes and inverted light-on-dark
 * codes such as the share cards generated by WeChat.
 */
export function decodeQrLuminance(source: LuminanceSource): string {
  let lastError: unknown;

  for (const candidate of [source, source.invert()]) {
    for (const Binarizer of [HybridBinarizer, GlobalHistogramBinarizer]) {
      try {
        const bitmap = new BinaryBitmap(new Binarizer(candidate));
        return new QRCodeReader().decode(bitmap, hints).getText();
      } catch (error) {
        lastError = error;
      }
    }
  }

  throw lastError instanceof Error ? lastError : new Error("QR code not found");
}

/**
 * Try grayscale as well as individual and combined colour channels. Separating
 * channels preserves contrast in multicolour QR codes whose colours have a
 * similar grayscale brightness.
 */
export function decodeQrPixels(pixels: Uint8ClampedArray, width: number, height: number): string {
  const pixelCount = width * height;
  const grayscale = new Uint8ClampedArray(pixelCount);
  const red = new Uint8ClampedArray(pixelCount);
  const green = new Uint8ClampedArray(pixelCount);
  const blue = new Uint8ClampedArray(pixelCount);
  const minimum = new Uint8ClampedArray(pixelCount);
  const maximum = new Uint8ClampedArray(pixelCount);

  for (let pixel = 0, offset = 0; pixel < pixelCount; pixel += 1, offset += 4) {
    const alpha = pixels[offset + 3] / 255;
    const r = Math.round(255 - (255 - pixels[offset]) * alpha);
    const g = Math.round(255 - (255 - pixels[offset + 1]) * alpha);
    const b = Math.round(255 - (255 - pixels[offset + 2]) * alpha);
    red[pixel] = r;
    green[pixel] = g;
    blue[pixel] = b;
    minimum[pixel] = Math.min(r, g, b);
    maximum[pixel] = Math.max(r, g, b);
    grayscale[pixel] = Math.round(0.299 * r + 0.587 * g + 0.114 * b);
  }

  let lastError: unknown;
  for (const channel of [grayscale, minimum, maximum, red, green, blue]) {
    try {
      return decodeQrLuminance(new RGBLuminanceSource(channel, width, height));
    } catch (error) {
      lastError = error;
    }
  }

  throw lastError instanceof Error ? lastError : new Error("QR code not found");
}

export async function decodeQrImage(file: Blob): Promise<string> {
  const objectUrl = URL.createObjectURL(file);

  try {
    const image = await loadImage(objectUrl);
    const scale = Math.min(1, MAX_IMAGE_EDGE / Math.max(image.naturalWidth, image.naturalHeight));
    const canvas = document.createElement("canvas");
    canvas.width = Math.max(1, Math.round(image.naturalWidth * scale));
    canvas.height = Math.max(1, Math.round(image.naturalHeight * scale));

    const context = canvas.getContext("2d", { willReadFrequently: true });
    if (!context) throw new Error("Canvas is not supported");

    // Transparent pixels should be treated as a light QR background.
    context.fillStyle = "#ffffff";
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.drawImage(image, 0, 0, canvas.width, canvas.height);

    const imageData = context.getImageData(0, 0, canvas.width, canvas.height);
    return decodeQrPixels(imageData.data, canvas.width, canvas.height);
  } finally {
    URL.revokeObjectURL(objectUrl);
  }
}

function loadImage(source: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.decoding = "async";
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error("Image could not be loaded"));
    image.src = source;
  });
}
